name: Generate APK

env:
  main_project_module: app
  target_owner: Xposed-Modules-Repo
  target_repo: io.github.jqssun.maceditor
  target_path: target_path

on:
  push:
    branches:
      - "release/**"
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "v*.*.*"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 检出仓库代码

      # 设置版本标签
      - name: Set TAG (push event)
        if: github.event_name == 'push'
        run: |
          echo "version=$(echo '${{ github.ref_name }}' | awk -F 'v' '{print $2}')" >> $GITHUB_ENV

      - name: Set TAG (workflow_dispatch event)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "version=$(echo '${{ inputs.version }}' | awk -F 'v' '{print $2}')" >> $GITHUB_ENV

      - name: Set ENV
        run: |
          echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      # 设置 JDK 环境
      - name: Use JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      # 构建 APK
      - name: Build APK
        run: |
          echo ${{ secrets.STORE }} | base64 -d > upload.jks
          echo ${{ secrets.LOCAL }} | base64 -d > local.properties
          chmod +x ./gradlew
          ./gradlew assembleRelease --stacktrace
          rm upload.jks local.properties

      # 使用 actions/upload-artifact@v3 上传 APK 工件
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk   # 工件名称
          path: ${{ env.main_project_module }}/build/outputs/apk/release/app-release.apk  # APK 文件路径

      # 如果你需要同步到 Xposed 仓库，也可以添加这部分，但这里不涉及权限问题
      - name: Checkout Xposed Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.target_owner }}/${{ env.target_repo }}
          path: ${{ env.target_path }}
          token: ${{ secrets.PAT }}

      - name: Sync
        run: |
          cd ${{ env.target_path }}
          cp ../README.md ../LICENSE .
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git add LICENSE
          git commit --amend --no-edit
          git push --force
